name: Pull Request Build Test
on: pull_request
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Check Format 
        run: yarn check-format
      - name: Check Types
        run: yarn check-types
      - name: Build
        run: yarn build
      - name: Compile 
        run: yarn compile:ci